name = "wordlelib"
description = "Library to track progress in a game of Wordle"
version = "0.1.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

licenses = "MIT"
tags = ["wordle", "game", "console", "terminal"]

[[depends-on]]
aaa = "~0.2.5"
